### ISSUE TITLE
Option to disable Proxy

### ISSUE THREAD

**Issue by switchtrue** [jenkinsci/google-compute-engine-plugin#132]
When a proxy server is configured for Jenkins, this plugin loads that proxy data when establishing the proxy connection.

https://github.com/jenkinsci/google-compute-engine-plugin/blob/875a671a4b9e2fc27e55c8977393df2d8f0e29c3/src/main/java/com/google/jenkins/plugins/computeengine/ComputeEngineLinuxLauncher.java#L187

In my configuration a proxy server is used for external traffic (e.g. download plugins) but my Jenkins master and Jenkins agents are on a private/internal IP address only and not accessible from the proxy server.

As such it would be good to have an option for this plugin to "Ignore Jenkins proxy settings" that would not load the Jenkins proxy settings even is set.

**Comment by stephenashank** [comment]
Hi @switchtrue, thanks for this suggestion! Our team is currently at [DevOps World](https://www.cloudbees.com/devops-world/san-francisco) but can look into this soon.

Given the small scope of this change, note that we also accept community contributions if you have the time and inclination. See [CONTRIBUTING.MD](https://github.com/jenkinsci/google-compute-engine-plugin/blob/master/CONTRIBUTING.md). Let me know if you have any questions.

Otherwise, We'll keep you updated on the progress here once we have the bandwidth for making and testing this change.

**Comment by stephenashank** [comment]
Fixed in #133, released with 4.0.0.
