### ISSUE TITLE
Issues adding GCE instance manually

### ISSUE THREAD

**Issue by rachely3n** [jenkinsci/google-compute-engine-plugin#39]
Unable to add GCE node (Manage Jenkins->Manage Nodes->New Node-> type name and select "google compute engine") because of error. 

I've seen a couple of users experience this issue although it is not our recommended workflow.

[Reference issue](https://issues.jenkins-ci.org/browse/JENKINS-55380)

**Comment by stephenashank** [comment]
Plugin removes need to manually provision instances.

**Comment by cmbasnett** [comment]
Shouldn't the correct response be to remove the ability to even encounter this error in the first place?

**Comment by stephenashank** [comment]
Thank you for the feedback. We've been in the process of clearing out our issue backlog, so when I initially responded I didn't have complete context on what was being asked and answered too quickly. After revisiting the issue I understand why we don't (and have no plans to) support provisioning nodes in the way the initial reporter described. It may be possible to make the response less jarring than angry Jenkins with a long stack trace, but actually fixing the issue would require a larger refactoring effort than we're able to commit to now.

When following the steps as listed, Jenkins expects there to be a configuration on the "ComputeEngineInstance" (the node itself) and fails without it. Instead, use the "Configure System" page to create a Google Compute Engine cloud and create an instance configuration with the desired label. Then on the "Manage Nodes" page, instead of using "New Node", use the "provision via ..." dropdown to select the label corresponding to the configuration, which will create a new node. I'll reference #145 here so that we keep this in mind when refreshing the usage documentation.

**Comment by jglick** [comment]
This is not a documentation issue IMO. Rather, the plugin fails to override `isInstantiable`.
