### ISSUE TITLE
Migrate to using managed instance groups

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-compute-engine-plugin#78]
A good amount of the instance provisioning, cleanup, and scaling logic can be eliminated from the code base by utilizing GCE's managed instance groups: https://cloud.google.com/compute/docs/instance-groups/

This would also solve some of outstanding issues with efficiency.

**Comment by viglesiasce** [comment]
Scaling with instance groups will be difficult since the IG is not aware of the workload running inside the instance. This could cause nodes to be taken out of service while long running jobs are running. Letting Jenkins do the instance provisioning allows it to decide when to take out which instance based on the knowledge of jobs running on the host.

**Comment by craigatgoogle** [comment]
The IG can be configured to scale by CPU utilization, which would result from agent workloads running on nodes, unless there's an aspect I'm missing.

**Comment by ingwarsw** [comment]
I personally think it will rather not work..
We have (and all jenkins nodes) have static number of workers per node.
We would have to make it dynamic and I really have no idea how it could work..

Could you elaborate how would you see it running?

**Comment by craigatgoogle** [comment]
The workers per node would still remain static, the internals of the Nodes wouldn't change. This would simply defer the node provisioning/de-provisioning logic to the managed instance group service.

This would however strip the Jenkins cloud of that responsibility which would probably require some no-op stubs for node creation/deletion. The bootstrapping will, (ie: the uploading of the JNLP agent jar), would still probably be required. That said, I'm not sure why we have that logic baked into the plugin rather than just publishing a default Instance template that has it baked in.

**Comment by ingwarsw** [comment]
@craigatgoogle But we have templates which gives such posibility.. and most people should using it :)
At least we are doing it, and it gives much more power that plugin itself..

And basically we could strip 3/4 logics of instance configuration, and leave only templates..
And to extend it to `managed instance group` it would require big rewrite force people to create and manage `managed instance groups` and then resizing group dynamically (Im not even sure if its possible to stop given instance in group, and that would be wrong to kill random one)
