### ISSUE TITLE
GCE autoscaling behavior not being observed

### ISSUE THREAD

**Issue by seanhui1** [jenkinsci/google-compute-engine-plugin#99]
When there are 2 build agents available, I run 3 jobs.  the 2 build agents pick up 2 jobs respectively(which does a sleep  for 30s), while the the 3rd job sits in the queue.

The behavior that I expected was that it would spin up a third build agent to pickup the third job.

Here are my configuration settings.

![2019-05-13_09-58-51](https://user-images.githubusercontent.com/2492484/57639871-be845100-7565-11e9-962f-b12747a4d6d4.png)
![2019-05-13_09-59-42](https://user-images.githubusercontent.com/2492484/57639915-dcea4c80-7565-11e9-8327-f1102213fe90.png)
![image](https://user-images.githubusercontent.com/2492484/57639938-ef648600-7565-11e9-982d-d1b655a38017.png)

**Comment by seanhui1** [comment]
Here are what my job configurations look like as well:

![image](https://user-images.githubusercontent.com/2492484/57640002-263a9c00-7566-11e9-8386-4997b911e0da.png)

**Comment by seanhui1** [comment]
here's an example of what my build queue looks like when I launch 3 jobs with one build agent currently available:

![image](https://user-images.githubusercontent.com/2492484/57641249-694a3e80-7569-11e9-8f68-31f966275635.png)

**Comment by rachely3n** [comment]
I need to investigate further, but it might be similar to https://github.com/jenkinsci/google-compute-engine-plugin/issues/57 where timing affects the number of instances launched for jobs.

**Comment by rachely3n** [comment]
Interesting, so I created 3 jobs (all have same label for which node it's restricted to run on) that take 45 seconds, 60 seconds, and 75 seconds. When the 45 second and 60 seconds ones are running, the third one is just stuck in the queue. I'll have to research some more.

**Comment by rachely3n** [comment]
When I ran the longest test first, only one instance was provisioned.

**Comment by seanhui1** [comment]
> Interesting, so I created 3 jobs (all have same label for which node it's restricted to run on) that take 45 seconds, 60 seconds, and 75 seconds. When the 45 second and 60 seconds ones are running, the third one is just stuck in the queue. I'll have to research some more.

@rachely3n how many nodes did you have available? 2?

**Comment by ingwarsw** [comment]
You know how cloud provisioning is `deciding` whatever to add new node or not?

Its complicated process.. which tries really hard to not spawn too many instances..
And there are few possibilities to tweak it..

To see how many executors are considered busy, free and needed see url:
`http://${your_jenkins_host}/label/${label_name}/load-statistics`

In default settings numbers of nodes should be as stable as possible..
So one extra node is not an issue..

Settings that are really aggressive and will force always provisioning new slave are (they should be used only with one shot agents, otherwise waaaay to many slaves will be spawn):
`-Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dhudson.model.LoadStatistics.clock=10000 -Dhudson.model.LoadStatistics.decay=0.2`

**Comment by seanhui1** [comment]
Ah, thanks for the information and explanation @ingwarsw .  It does seem to be timing based.

Have you guys considered being able to configure the provisioning process like the settings you mentioned via the plugin? @rachely3n

**Comment by rachely3n** [comment]
Closing as parameters that adjust timing are part of jenkins core, and autoscaling features are seen more explicitly with more instances/nodes launched.
